/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package local.ci.first;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test public void testAppHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }

    @Test public void testSum() {
        App testApp = new App();
        assertEquals(9, testApp.calc(3));
        assertEquals(81, testApp.calc(9));
    }
}
